# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Increment Version

on:
  push:
    branches: [ "main" ]

jobs:
  build:
#type of runner that the job will run upon
    runs-on: ubuntu-latest

    steps:
    - name: Step1 - Checkout main branch from Github
      uses: actions/checkout@v3
    
    - name: Step2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step3 - Increment Maven Version
      run: mvn clean install -Drevision=1.0.0
    - name: Step4 - Commit POM changes to GIT
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: POM Version Update

   
